name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.1
  firebase_analytics: ^7.1.1
  firebase_database: any
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  flutter_search_bar: ^2.1.0
  english_words: ^4.0.0
  provider: ^4.0.2
  flutter_login: ^1.0.14
  shared_preferences: ^2.0.4
  modal_progress_hud: ^0.1.3
  http: ^0.13.0
  #dio: ^3.0.9
  #path_provider: ^1.6.5
  #downloads_path_provider_28: ^0.1.0
  #permission_handler: ^4.4.0+hotfix.2
  #open_file: ^3.0.1
  #flutter_local_notifications: ^1.3.0
  #firebase_storage: ^3.0.8
  #scoped_model: ^1.0.1
  #dio: 1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # cloud_firestore: ^0.13.0+1
  #firebase_auth: ^0.15.3+1
  #firebase_core: ^0.4.3+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  gradient_widgets: ^0.5.1
flutter_icons:
    ios: true
    android: true
    image_path_ios: "assets/launcher/icon11.png"
    image_path_android: "assets/launcher/icon11.png"
    adaptive_icon_background: "assets/launcher/background1.png"
    adaptive_icon_foreground: "assets/launcher/icon11.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/c++.png
    - assets/java.png
    - assets/java 8.png
    - assets/LetUsC.png
    - assets/python.png
    - assets/coders at work.png
    - assets/foreground.png
    - assets/logo.png



module:
  androidX: true
  androidPackage: com.example.book_bank
  iosBundleIdentifier: com.example.book_bank
























